      - name: Generate changelog for version tags
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          echo "" >> CHANGELOG.md
          echo "## Version ${{ github.ref_name }}" >> CHANGELOG.md
          CHANGES=$(git log --oneline --no-decorate $(git describe --tags --abbrev=0 @^)..@)
          if [ -z "$CHANGES" ]; then
            echo "No changes since previous version." >> CHANGELOG.md
          else
            echo "$CHANGES" >> CHANGELOG.md
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Update changelog for ${{ github.ref_name }}"
          git push origin HEAD:main
name: Auto Tag on Push
on:
  push:
    branches:
      - '**'
    tags:
      - '*'
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print PAT (debug)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          if [[ ! "$GITHUB_REF" =~ ^refs/tags/v ]]; then
            TAG_NAME="auto-xp_core-$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
            git tag "$TAG_NAME"
            git fetch --unshallow || true
            git remote remove authtemp || true
            git remote add authtemp https://x-access-token:$GH_PAT@github.com/$GITHUB_REPOSITORY
            git push authtemp "$TAG_NAME"
          fi
          # Update changelog for version tags
          if [[ "$GITHUB_REF" =~ ^refs/tags/v ]]; then
            VERSION_TAG="${GITHUB_REF##*/}"
            echo "" >> CHANGELOG.md
            echo "## Version $VERSION_TAG" >> CHANGELOG.md
            CHANGES=$(git log --oneline --no-decorate $(git describe --tags --abbrev=0 @^)..@)
            if [ -z "$CHANGES" ]; then
              echo "No changes since previous version." >> CHANGELOG.md
            else
              echo "$CHANGES" >> CHANGELOG.md
            fi
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add CHANGELOG.md
            git commit -m "Update changelog for $VERSION_TAG"
            git push origin HEAD:main
          fi
