name: Auto Tag and Changelog

on:
  push:
    branches:
      - main

jobs:
  tag-and-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Bump version and create tag
        id: bump_version
        run: |
          NEW_TAG=$(python scripts/bump_version.py)
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "New tag: $NEW_TAG"
      
      - name: Update changelog
        run: |
          python scripts/update_changelog.py ${{ steps.bump_version.outputs.new_tag }}
      
      - name: Commit and push changelog
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update changelog for ${{ steps.bump_version.outputs.new_tag }}" || echo "No changes to commit"
          git push
      
      - name: Push tag
        run: |
          git push origin ${{ steps.bump_version.outputs.new_tag }}
