name: Auto Tag on Push
on:
  push:
    branches:
      - 'disabled-temporarily'  # Temporarily disabled to stop recursion
    tags:
      - 'disabled-temporarily'

jobs:
  tag:
    runs-on: ubuntu-latest
    # Skip if this is a changelog update commit to prevent recursion
    if: "!contains(github.event.head_commit.message, 'Update changelog for')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for git describe
          
      - name: Auto-tag non-version pushes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          if [[ ! "$GITHUB_REF" =~ ^refs/tags/v ]]; then
            TAG_NAME="auto-xp_core-$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
            git tag "$TAG_NAME"
            git fetch --unshallow || true
            git remote remove authtemp || true
            git remote add authtemp https://x-access-token:$GH_PAT@github.com/$GITHUB_REPOSITORY
            git push authtemp "$TAG_NAME"
          fi
          
      - name: Update changelog for version tags
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION_TAG="${GITHUB_REF##*/}"
          echo "" >> CHANGELOG.md
          echo "## Version $VERSION_TAG" >> CHANGELOG.md
          
          # Get changes since last version tag, filtering out changelog updates
          LAST_TAG=$(git describe --tags --abbrev=0 @^ 2>/dev/null || echo "")
          if [ -n "$LAST_TAG" ]; then
            CHANGES=$(git log --oneline --no-decorate $LAST_TAG..@ 2>/dev/null | grep -v "Update changelog for" || echo "")
          else
            CHANGES=$(git log --oneline --no-decorate 2>/dev/null | grep -v "Update changelog for" || echo "")
          fi
          
          if [ -z "$CHANGES" ]; then
            echo "- No meaningful changes since previous version." >> CHANGELOG.md
          else
            echo "$CHANGES" | sed 's/^/- /' >> CHANGELOG.md
          fi
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Update changelog for $VERSION_TAG"
          git push origin HEAD:main